language: php
php:
- 5.4
env:
- DB=pgsql
before_script:
- sh -c "psql -f ./database/example.sql -U postgres;"
- mkdir ./deploy_root/app/tmp
- chmod -R 777 ./deploy_root/app/tmp
- sudo apt-get install lighttpd
- sh -c "pear channel-discover pear.cakephp.org"
- sh -c "pear install --alldeps cakephp/CakePHP_CodeSniffer;"
- phpenv rehash
- set +H
- cp deploy_root/app/Config/database-travis.php deploy_root/app/Config/database.php
script:
- sh -c "phpcs -p --extensions=php --standard=CakePHP ./deploy_root/lib/Cake; "
- sh -c "./deploy_root/lib/Cake/Console/cake test core AllDbRelated --stderr"
notifications:
  email: false
  hipchat:
    rooms:
      secure: QfR/rozMt6KhfoVRspfnIwKRs+PpO0DULyQ7ub5pysh93HwHLVM1LnPdJNt4KGkV5rNfIgqDaBBF2kEbYObf3zyjSekDFbTYHkcrACxYQy+2N3WSuNGRw9gPIRydQHjv9t4EbgpdVJTG3LlFfZxD5of5FWYRL4Mlqplgu8X6FuE=
